---
- name: Backup files
  include_tasks: backup.yml

- name: Load platform variables
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/vars/{{ vyos_platform }}.yml"
    - "{{ role_path }}/vars/generic.yml"

- name: Copy custom debs
  include_tasks: copy.yml

- name: Install deb packages
  include_tasks: install-debs.yml

- name: Cleanup temporary files
  include_tasks: cleanup.yml

- name: Restore files
  include_tasks: restore.yml