---
- hosts: hyperv
  become: true
  gather_facts: true
  connection: local
  vars:
    cloud_init: "true"
    cloud_init_ds_list: "{{ cloud_init_ds_string.split(',') }}"
    cloud_init_ds_string: "{{ cloud_init_ds | default('NoCloud, Azure, None') }}"
    custom_packages: true
    disk_size: 2
    grub_console: serial
    parttable_type: hybrid
    vyos_format: vhd
    vyos_hyperv_img: /tmp/vyos_azure_image.vhd
    vyos_images_dir: /tmp
    vyos_output_img: "{{ vyos_hyperv_img }}"
    vyos_platform: azure
    without_login: true
  roles:
    - install-packages
    - mount-iso
    - get-version
    - create-disk
    - setup-root-partition
    - install-image
    - mount-root-fs
    - install-config
    - install-grub
    - install-persistence-conf
    - install-cloud-init-wrapper
    - install-custom-packages-wrapper
    - unmount-pre
    - unmount-all
    - azure-vhd
    - cleanup-ending
    - release
